- name: Create list of host IDs which has running non-migratable VM and are not down
  set_fact:
    host_ids_items: "{{ item.host.id }}"
  with_items:
    - "{{ ovirt_vms | default([]) }}"
  when:
    - "item['placement_policy']['affinity'] != 'migratable'"
    - "item.host is defined"
  loop_control:
    label: "{{ item.name }}" 
  register: host_ids_result

- name: Create list of host IDs which has pinned VM
  set_fact:
    host_ids: "{{ host_ids_result.results | rejectattr('ansible_facts', 'undefined') | map(attribute='ansible_facts.host_ids_items') | list }}"

- block:
  - name: Shutdown non-migratable VMs
    ovirt_vms:
      auth: "{{ ovirt_auth }}"
      state: stopped
      force: true
      name: "{{ item.name }}"
    with_items:
      - "{{ ovirt_vms }}"
    when:
      - "item['placement_policy']['affinity'] != 'migratable'"
      - "item.host is defined"
      - "item.host.id in ovirt_hosts | map(attribute='id')"  # Ensure we stop only pinned VMs which run on hosts to be upgraded.
    loop_control:
      label: "{{ item.name }}"
    register: pinned_to_host_vms

  - name: Create list of VM names which was shutted down
    set_fact:
      pinned_vms_names: "{{ pinned_to_host_vms.results | selectattr('changed') | map(attribute='item.name') | list }}"

  when: stop_non_migratable_vms
