---
################################
## User & groups internal
################################
- name: Manage internal users
  command: "{{ aaa_jdbc_prefix }}/ovirt-aaa-jdbc-tool user {{ (item.state is undefined or item.state == 'present') | ternary('add','delete') }} {{ item.name }}"
  with_items:
    - "{{ users | default([]) }}"
  register: out_users
  changed_when: "out_users.rc != 5 and out_users.rc != 4"
  # 5 == user already exists
  # 4 == no user to be removed
  # 0 == all OK
  failed_when: "out_users.rc != 5 and out_users.rc != 0 and out_users.rc != 4"
  tags:
    - ovirt-aaa-jdbc
    - users

- name: Update users according to attributes
  command: "{{ aaa_jdbc_prefix }}/ovirt-aaa-jdbc-tool user edit {{ item.name }} {% for attr, value in item['attributes'].iteritems() %} --attribute={{ attr }}='{{ value }}' {% endfor %}"
  with_items:
    - "{{ users | default([]) }}"
  register: out_users
  when: "item.attributes is defined"
  changed_when: "out_users.rc != 5 and out_users.rc != 4"
  # 5 == user already exists
  # 4 == no user to be removed
  # 0 == all OK
  failed_when: "out_users.rc != 5 and out_users.rc != 0 and out_users.rc != 4"
  tags:
    - ovirt-aaa-jdbc
    - users

# FIXME: when user try to change the password which was already set in history
# but is not current password we continue with changed=false:
- name: Manage internal users passwords
  no_log: true
  command: "{{ aaa_jdbc_prefix }}/ovirt-aaa-jdbc-tool user password-reset {{ item.name }} --password=\"pass:{{ item.password }}\" --password-valid-to=\"{{ item.valid_to }}\""
  with_items:
    - "{{ users | default([]) }}"
  register: out_users
  changed_when: "out_users.rc != 1"
  failed_when: "out_users.rc != 1 and out_users.rc != 0"
  tags:
    - ovirt-aaa-jdbc
    - users

- name: Manage internal groups
  command: "{{ aaa_jdbc_prefix }}/ovirt-aaa-jdbc-tool group {{ (item.state is undefined or item.state == 'present') | ternary('add','delete') }} {{ item.name }}"
  with_items:
    - "{{ user_groups | default([]) }}"
  register: out_groups
  changed_when: "out_groups.rc != 5 and out_groups.rc != 4"
  failed_when: "out_groups.rc != 5 and out_groups.rc != 0 and out_groups.rc != 4"
  tags:
    - ovirt-aaa-jdbc
    - user_groups

# FIXME: Support only add, if the user is removed from list, it's not removed from the group:
- name: Manage groups members
  command: "{{ aaa_jdbc_prefix }}/ovirt-aaa-jdbc-tool group-manage {{ (item.state is undefined or item.state == 'present') | ternary('useradd','userdel') }} {{ item.0.name }} --user {{ item.1 }}"
  with_subelements:
    - "{{ user_groups | default([]) }}"
    - users
  register: out_group_member
  changed_when: "out_group_member.rc != 3 "
  failed_when: "out_group_member.rc != 3 and out_group_member.rc != 0"
  tags:
    - ovirt-aaa-jdbc
    - user_groups
