- name: "Get info about VM {{current_vm.name }}"
  ovirt_vms_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ current_vm.name }}"

- name: "Create VM {{current_vm.name }}"
  # TODO: Change when Ansible 2.4 is released:
  # ovirt_vms:
  ovirt_vms_24:
    auth: "{{ ovirt_auth }}"
    state: "{{ (ovirt_vms | length > 0) | ternary('present', 'stopped') }}"
    name: "{{ current_vm.name }}"
    cluster: "{{ current_vm.profile.cluster | default(omit) }}"
    template: "{{ current_vm.profile.template | default(omit) }}"
    memory: "{{ current_vm.profile.memory | default(omit) }}"
    cpu_cores: "{{ current_vm.profile.cores | default(omit) }}"
    memory_guaranteed: "{{ current_vm.profile.memory_guaranteed | default(omit) }}"
    cpu_sockets: "{{ current_vm.profile.sockets | default(omit) }}"
    high_availability: "{{ current_vm.profile.high_availability | default(omit) }}"
    storage_domain: "{{ current_vm.profile.storage_domain | default(omit) }}"
    timeout: "{{ vm_infra_create_single_timeout }}"
  changed_when: false
  async: "{{ vm_infra_create_single_timeout }}"
  poll: 0
  register: added_vm

- set_fact:
    all_vms: "{{ all_vms | default([]) + [added_vm] }}"
