# To keep legacy cloud init parameters we need this:
- name: Manage state
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: "{{ current_vm.profile.state | default('running') }}"
    name: "{{ current_vm.name }}"
    cloud_init:
      host_name: "{{ current_vm.name }}.{{ current_vm.profile.domain | default(omit) }}"
      authorized_ssh_keys: "{{ current_vm.profile.ssh_key | default('') }}"
      user_name: "{{ current_vm.profile.root_password is defined | ternary('root', omit) }}"
      root_password: "{{ current_vm.profile.root_password | default(omit) }}"
    cloud_init_nics: "{{ current_vm.cloud_init_nics | default(omit) }}"
    timeout: "{{ vm_infra_create_single_timeout }}"
  changed_when: false
  async: "{{ vm_infra_create_single_timeout }}"
  poll: 0
  register: legacy_started_vm
  when: current_vm.profile.root_password is defined or current_vm.profile.domain is defined or current_vm.profile.ssh_key is defined

- set_fact:
    started_vms: "{{ started_vms|default([]) + [legacy_started_vm] }}"
  when: not (legacy_started_vm.skipped | default(false))

- name: Manage state
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: "{{ current_vm.profile.state | default('running') }}"
    name: "{{ current_vm.name }}"
    cloud_init: "{{ current_vm.cloud_init | default(omit) }}"
    cloud_init_nics: "{{ current_vm.cloud_init_nics | default(omit) }}"
    timeout: "{{ vm_infra_create_single_timeout }}"
  changed_when: false
  async: "{{ vm_infra_create_single_timeout }}"
  poll: 0
  register: started_vm
  when: (current_vm.cloud_init is defined) or legacy_started_vm.skipped | default(false)

- set_fact:
    started_vms: "{{ started_vms|default([]) + [started_vm] }}"
  when: not (started_vm.skipped | default(false))
