---
#################################################
# Storages
#################################################
# First add master storage
- name: Add master storage
  ovirt_storage_domains:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.value.state | default(omit) }}"
    name: "{{ item.key }}"
    domain_function: "{{ item.value.domain_function | default(omit) }}"
    host: "{{ hosts[0].name }}"
    data_center: "{{ data_center_name }}"
    nfs: "{{ item.value.nfs | default(omit) }}"
    iscsi: "{{ item.value.iscsi | default(omit) }}"
    posixfs: "{{ item.value.posixfs | default(omit) }}"
    glusterfs: "{{ item.value.glusterfs | default(omit) }}"
    fcp: "{{ item.value.fcp | default(omit) }}"
  with_dict: "{{ storages | default({}) }}"
  when: item.value.master is defined and item.value.master
  tags:
    - storages

# Next add rest of data storages
- name: Add storages
  ovirt_storage_domains:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.value.state | default(omit) }}"
    name: "{{ item.key }}"
    domain_function: "{{ item.value.domain_function | default(omit) }}"
    host: "{{ hosts[0].name }}"
    data_center: "{{ data_center_name }}"
    nfs: "{{ item.value.nfs | default(omit) }}"
    iscsi: "{{ item.value.iscsi | default(omit) }}"
    posixfs: "{{ item.value.posixfs | default(omit) }}"
    glusterfs: "{{ item.value.glusterfs | default(omit) }}"
    fcp: "{{ item.value.fcp | default(omit) }}"
  with_dict: "{{ storages | default({}) }}"
  when: item.value.domain_function is not defined
  tags:
    - storages

# Next add export/iso storages
- name: Add export/iso storages
  ovirt_storage_domains:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.value.state | default(omit) }}"
    name: "{{ item.key }}"
    domain_function: "{{ item.value.domain_function | default(omit) }}"
    host: "{{ hosts[0].name }}"
    data_center: "{{ data_center_name }}"
    nfs: "{{ item.value.nfs | default(omit) }}"
    iscsi: "{{ item.value.iscsi | default(omit) }}"
    posixfs: "{{ item.value.posixfs | default(omit) }}"
    glusterfs: "{{ item.value.glusterfs | default(omit) }}"
    fcp: "{{ item.value.fcp | default(omit) }}"
  with_dict: "{{ storages | default({}) }}"
  when: item.value.domain_function is defined
  tags:
    - storages

- name: Fetch storages
  ovirt_storage_domains_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "type=nfs or type=iscsi or type=posixfs or type=glusterfs or type=fcp"
    #pattern: "type=nfs or type=posixfs or type=glusterfs"
    #pattern: "type=iscsi or type=fcp"
    fetch_nested: true
  tags:
    - storages

- name: Validate connections of storages
  ovirt_storage_connections:
    auth: "{{ ovirt_auth }}"
    id: "{{ item.1.id[0] }}"
    storage: "{{ item.0.name }}"
    address: "{{ storages[item.0.name][item.0.storage.type].address | default(omit) }}"
    path: "{{ storages[item.0.name][item.0.storage.type].path | default(omit) }}"
    nfs_timeout: "{{ storages[item.0.name][item.0.storage.type].timeout | default(omit) }}"
    nfs_version: "{{ storages[item.0.name][item.0.storage.type].version | default(omit) }}"
    nfs_retrans: "{{ storages[item.0.name][item.0.storage.type].retrans | default(omit) }}"
    mount_options: "{{ storages[item.0.name][item.0.storage.type].mount_options | default(omit) }}"
    username: "{{ storages[item.0.name][item.0.storage.type].username | default(omit) }}"
    password: "{{ storages[item.0.name][item.0.storage.type].password | default(omit) }}"
    port: "{{ storages[item.0.name][item.0.storage.type].port | default(omit) }}"
    target: "{{ storages[item.0.name][item.0.storage.type].target | default(omit) }}"
    force: true
  with_subelements:
    - "{{ ovirt_storage_domains | default([]) }}"
    - storage_connections
  when: item.0.name in storages
  tags:
    - storages
