galaxy_info:
  author: Ondra Machacek
  description: Role to deploy ManageIQ/CloudForms into oVirt/RHV.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.3

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 24

  galaxy_tags: [manageiq, cloudforms, ovirt, rhv, rhev, virtualization]

dependencies: []
