---
### ManageIQ/CloudForms ###

# QCOW2 ManageIQ/CloudForms image URL:
miq_qcow_url: http://releases.manageiq.org/manageiq-ovirt-fine-1.qc2
miq_image_path: /tmp/ovirt_image_data
miq_qcow_checksum: sha256:b3644e8ac75af9663d19372e21b8a0273d68e54bfd515518321d3102d08daebd
miq_username: admin
miq_password: smartvm

# Providers:
miq_rhv_provider_name: RHV provider

### oVirt/RHV ###
# VM variables:
miq_vm_name: manageiq_fine
miq_vm_cluster: Default
miq_vm_memory: 6GiB
miq_vm_cpu: 2
miq_vm_os: rhel_7x64

# Vm disks
miq_vm_disk_size: 50GiB
miq_vm_disk_interface: virtio
miq_vm_disk_format: cow

# Vm NICS:
miq_vm_nics:
  - name: nic1
    profile_name: ovirtmgmt
    interface: virtio
