galaxy_info:
  author: Ondra Machacek
  description: Role to upgrade single host in oVirt/RHV.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions:
      - all
  - name: Fedora
    versions:
      - all

  galaxy_tags: [ovirt, rhv, rhev, virtualization]

dependencies: []
