galaxy_info:
  author: Katerina Koukiou
  description: Role to cleanup datacenters in oVirt.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.4

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - all

  galaxy_tags: [ovirt, rhv, rhev, virtualization]

dependencies: []
