galaxy_info:
  author: Ondra Machacek
  description: Role to deploy oVirt hypervisor.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.3

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 25

  galaxy_tags: [ovirt, rhv, rhev, virtualization]

dependencies:
  - ovirt-host-deploy-facts
  - ovirt-provider-ovn-driver
  - ovirt-host-deploy-firewalld
