---
# stop_pinned_to_host_vms is alias for stop_non_migratable_vms
stop_non_migratable_vms: "{{ stop_pinned_to_host_vms | default(false) }}"
upgrade_timeout: 1200
cluster_name: Default
check_upgrade: false
host_statuses:
  - up
host_names:
  - '*'
