- name: Find existing Hosts
  ovirt_hosts_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "cluster={{ cluster_item.name }}"

- name: Remove Hosts
  ovirt_hosts:
    state: absent
    name: "{{ host_item.name }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_hosts }}"
  loop_control:
    loop_var: host_item

- name: Remove Cluster
  ovirt_cluster:
    state: absent
    name: "{{ cluster_item.name }}"
    auth: "{{ ovirt_auth }}"
