- name: Find existing Disks
  ovirt_disks_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove Disks
  ovirt_disks:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_disks }}"
  when: ovirt_item.name != 'OVF_STORE'
  loop_control:
    loop_var: ovirt_item
