- name: Find existing Templates
  ovirt_templates_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove Templates
  ovirt_templates:
    state: absent
    auth: "{{ ovirt_auth }}"
    id: "{{ ovirt_item.id }}"
  with_items: "{{ ovirt_templates }}"
  when: ovirt_item.name != 'Blank'
  loop_control:
    loop_var: ovirt_item
